track the # of errors during runtest and spit out the # of failed tests when it's done (for automated build validation using 'make test')

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -21,11 +21,21 @@ while IFS=':' read action line;do
 
 	/bin/echo -n "	$txt "
 	case $action in
-	y) test "$rc" -eq 0 && echo "passed" || echo "failed" ;;
-	n) test "$rc" -eq 0 && echo "failed" || echo "passed" ;;
+	y)  if test "$rc" -eq 0 ; then
+		echo "passed"
+	    else
+		echo "failed"
+		(( failed ++ ))
+	    fi ;;
+	n) if test "$rc" -eq 0 ; then
+		echo "failed"
+		(( failed ++ ))
+	    else
+		echo "passed"
+	    fi ;;
 	*) test "$rc" -eq 0 && echo "ok" || echo "$MSG"   ;;
 	esac
     fi
 done
 test -z "$last" || echo
-exit 0
+exit $failed
